# ==================
# Environment
# ==================
environment: development

# ==================
# Base
# ==================
title: Alex Pate - Digital Designer
description: > #
    Alex Pate is a digital designer and front-end developer from London, currently looking for a full-time job!

url: "http://127.0.0.1:4000"

# ==================
# Author
# ==================
name: Alex Pate
author:
    name: Alex Pate
    firstname: Alexander
    lastname: Pate
    nickname: Alex
    description: "I'm a digital developer, mostly working with the front-end (but I know my way around Laravel). I'm currently a front-end developer at Pusher."

email: alex@alexpate.uk
email_secure: "&#097;&#108;&#101;&#120;&#064;&#097;&#108;&#101;&#120;&#112;&#097;&#116;&#101;&#046;&#117;&#107;"

social:
    twitter: "https://twitter.com/alexjpate"
    twitter_handle: "alexjpate"
    github: "https://github.com/alexpate"
    dribbble: "https://dribbble.com/alexpate"
    instagram: "https://instagram.com/alexjpate"
    google: "https://plus.google.com/+AlexanderPate"

availability:
    class: full

# ============================
# Pagination
# ============================
paginate: 3
permalink: /journal/:title
paginate_path: /journal/page/:num

collections:
    work:
        output: true
        permalink: /:path/

# ==================
# Building
# ==================
exclude: [
    "Gemfile",
    "Gemfile.lock"
]

gems: [jekyll-assets, rouge, autoprefixer-rails, jekyll-sitemap]

markdown: kramdown

kramdown:
    input: GFM
    css_class: highlight

# ==================
# Assets
# ==================
sass:
    sass_dir: assets/stylesheets

assets:
    baseurl: http://127.0.0.1:4000/assets/
    cache: false
    cachebust: none
    css_compressor: sass
    js_compressor: uglifier
    debug: true
    sources:
        - assets/